# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
# JDK 8 is not supported
#  - oraclejdk8
# JDK 7 is set to deploy the docs in the configuration matrix
#  - oraclejdk7
  - openjdk7
env:
  - SERVER=jetty
  - SERVER=tomcat7
matrix:
  include:
    # Documentation deployed with JDK7
    - jdk: oraclejdk7
      env: SERVER=jetty DEPLOY_DOCS=true
    - jdk: oraclejdk7
      env: SERVER=tomcat7

before_install:
  # Gets scripts
  - git clone -b v0.4.2 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
script:
  # Unit and integration tests are run
  - mvn clean verify -P $SERVER
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment,$SERVER
