# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
matrix:
  include:
    # Documentation deployed with Open JDK7
    - jdk: openjdk7
      env: SERVER=jetty DEPLOY_DOCS=true
    - jdk: openjdk7
      env: SERVER=tomcat7

before_install:
  # Gets scripts
  - git clone -b v1.0.0 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
script:
  # Unit and integration tests are run
  - mvn clean verify -P $SERVER
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment,$SERVER
